### ISSUE TITLE
[book errata] Including Legacy C code - how to do it

### ISSUE THREAD

**Issue by owlfox** [PacktPublishing/Rust-Programming-Cookbook#6]
Hi,
I followed the book instruction on [safari online](https://learning.oreilly.com/library/view/rust-programming-cookbook/9781789530667/4deaf2a6-1732-47d4-ae98-183ab23664de.xhtml)
```
$ cd rust-digest/target/release
$ LD_LIBRARY_PATH=$(pwd)
$ echo $LD_LIBRARY_PATH 
/tmp/Rust-Cookbook/Chapter07/legacy-c-code/rust-digest/target/release
$ ./target/main
```
but got:
```
./target/main: error while loading shared libraries: libdigest.so: cannot open shared object file: No such file or directory
```
In bash, we should also export LD_LIBRARY_PATH. I think adding `ldd` to double check libdigest.so is found would be nice 😀.
Or can we make it a static binary?

**Comment by celaus** [comment]
Hi! 

Yes indeed the LD_LIBRARY_PATH should be exported (my bad, we'll add that to the known issues) to be available and you are right checking with `ldd` makes it clear. I'll find out how we can make this available to other readers. 

Thank you!

**Comment by sonam-packt** [comment]
Thank you Celaus!
